baseurl = "/"
languageCode = "en-us"
title = "Ziroby's musings"
theme = "hugo-strata-theme"
disqusShortname = "ziroby"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Ron 'Ziroby' Romero"
	description = "A collection of Ziroby's musings on life"

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	# Add read time estimates in the format "X min read"
	show_read_time = false

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "avatar.jpg"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "Ziroby's musings"
		# The icons will be shown if you enter your username
		twitter = "ziroby"
		github = "ziroby"
		#gitlab = "ziroby"
		dribbble = ""
		facebook = "ziroby"
		googleplus = ""
		flickr = ""
		linkedin = "ronromero"

		copyright = [
			"&copy; 2020 Ron Ziroby Romero",
		]


	[params.about]
		hide  = false
		title = "Ipsum lorem dolor aliquam ante commodo magna sed accumsan arcu neque."
		content = "Accumsan orci faucibus id eu lorem semper. Eu ac iaculis ac nunc nisi lorem vulputate lorem neque cubilia ac in adipiscing in curae lobortis tortor primis integer massa adipiscing id nisi accumsan pellentesque commodo blandit enim arcu non at amet id arcu magna. Accumsan orci faucibus id eu lorem semper nunc nisi lorem vulputate lorem neque cubilia."


	[params.portfolio]
		hide  = false
		title = "Recent Work"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like


	[[params.portfolio.gallery]]
		image = "at-the-bear/cartoon1560545808077.jpg"
		thumb = "at-the-bear/thumbs/cartoon1560545808077.jpg"
		title = "Title cartoon1560545808077.jpg"
		description = "2020-02-13T22:25:26+00:00"

	[[params.portfolio.gallery]]
		image = "at-the-bear/cartoon1562445936834.jpg"
		thumb = "at-the-bear/thumbs/cartoon1562445936834.jpg"
		title = "Title cartoon1562445936834.jpg"
		description = "2020-02-13T22:25:26+00:00"

	[[params.portfolio.gallery]]
		image = "at-the-bear/cartoon1565987322011.jpg"
		thumb = "at-the-bear/thumbs/cartoon1565987322011.jpg"
		title = "Title cartoon1565987322011.jpg"
		description = "2020-02-13T22:25:26+00:00"

	[[params.portfolio.gallery]]
		image = "at-the-bear/cartoon1566641576119.jpg"
		thumb = "at-the-bear/thumbs/cartoon1566641576119.jpg"
		title = "Title cartoon1566641576119.jpg"
		description = "2020-02-13T22:25:26+00:00"

	[[params.portfolio.gallery]]
		image = "at-the-bear/cartoon1567198102604.jpg"
		thumb = "at-the-bear/thumbs/cartoon1567198102604.jpg"
		title = "Title cartoon1567198102604.jpg"
		description = "2020-02-13T22:25:26+00:00"

	[[params.portfolio.gallery]]
		image = "at-the-bear/cartoon1567883945167.jpg"
		thumb = "at-the-bear/thumbs/cartoon1567883945167.jpg"
		title = "Title cartoon1567883945167.jpg"
		description = "2020-02-13T22:25:26+00:00"

	[[params.portfolio.gallery]]
		image = "at-the-bear/cartoon1567890129252.jpg"
		thumb = "at-the-bear/thumbs/cartoon1567890129252.jpg"
		title = "Title cartoon1567890129252.jpg"
		description = "2020-02-13T22:25:26+00:00"

	[[params.portfolio.gallery]]
		image = "at-the-bear/cartoon1568400390980-01.jpeg"
		thumb = "at-the-bear/thumbs/cartoon1568400390980-01.jpeg"
		title = "Title cartoon1568400390980-01.jpeg"
		description = "2020-02-13T22:25:26+00:00"

	[[params.portfolio.gallery]]
		image = "at-the-bear/cartoon1568406798003-01.jpeg"
		thumb = "at-the-bear/thumbs/cartoon1568406798003-01.jpeg"
		title = "Title cartoon1568406798003-01.jpeg"
		description = "2020-02-13T22:25:26+00:00"

	[[params.portfolio.gallery]]
		image = "at-the-bear/cartoon1571431675510-01.jpeg"
		thumb = "at-the-bear/thumbs/cartoon1571431675510-01.jpeg"
		title = "Title cartoon1571431675510-01.jpeg"
		description = "2020-02-13T22:25:26+00:00"

	[[params.portfolio.gallery]]
		image = "at-the-bear/cartoon1571674470259.jpg"
		thumb = "at-the-bear/thumbs/cartoon1571674470259.jpg"
		title = "Title cartoon1571674470259.jpg"
		description = "2020-02-13T22:25:26+00:00"

	[[params.portfolio.gallery]]
		image = "at-the-bear/IMG_20191005_204534-01.jpeg"
		thumb = "at-the-bear/thumbs/IMG_20191005_204534-01.jpeg"
		title = "Title IMG_20191005_204534-01.jpeg"
		description = "2020-02-13T22:25:26+00:00"

	[[params.portfolio.gallery]]
		image = "at-the-bear/IMG_20191018_195016-01.jpeg"
		thumb = "at-the-bear/thumbs/IMG_20191018_195016-01.jpeg"
		title = "Title IMG_20191018_195016-01.jpeg"
		description = "2020-02-13T22:25:26+00:00"

	[[params.portfolio.gallery]]
		image = "at-the-bear/IMG_20191103_150800.jpg"
		thumb = "at-the-bear/thumbs/IMG_20191103_150800.jpg"
		title = "Title IMG_20191103_150800.jpg"
		description = "2020-02-13T22:25:26+00:00"

	[[params.portfolio.gallery]]
		image = "at-the-bear/IMG_20191103_152450.jpg"
		thumb = "at-the-bear/thumbs/IMG_20191103_152450.jpg"
		title = "Title IMG_20191103_152450.jpg"
		description = "2020-02-13T22:25:26+00:00"

	[[params.portfolio.gallery]]
		image = "at-the-bear/IMG_20191103_155649.jpg"
		thumb = "at-the-bear/thumbs/IMG_20191103_155649.jpg"
		title = "Title IMG_20191103_155649.jpg"
		description = "2020-02-13T22:25:26+00:00"

	[[params.portfolio.gallery]]
		image = "at-the-bear/IMG_20191103_155801.jpg"
		thumb = "at-the-bear/thumbs/IMG_20191103_155801.jpg"
		title = "Title IMG_20191103_155801.jpg"
		description = "2020-02-13T22:25:26+00:00"

	[[params.portfolio.gallery]]
		image = "at-the-bear/IMG_20191105_215937_427.jpg"
		thumb = "at-the-bear/thumbs/IMG_20191105_215937_427.jpg"
		title = "Title IMG_20191105_215937_427.jpg"
		description = "2020-02-13T22:25:26+00:00"

	[[params.portfolio.gallery]]
		image = "at-the-bear/IMG_20191105_215937_436.jpg"
		thumb = "at-the-bear/thumbs/IMG_20191105_215937_436.jpg"
		title = "Title IMG_20191105_215937_436.jpg"
		description = "2020-02-13T22:25:26+00:00"

	[[params.portfolio.gallery]]
		image = "at-the-bear/IMG_20191105_215937_451.jpg"
		thumb = "at-the-bear/thumbs/IMG_20191105_215937_451.jpg"
		title = "Title IMG_20191105_215937_451.jpg"
		description = "2020-02-13T22:25:26+00:00"

	[[params.portfolio.gallery]]
		image = "at-the-bear/inCollage_20190331_004537852.jpg"
		thumb = "at-the-bear/thumbs/inCollage_20190331_004537852.jpg"
		title = "Title inCollage_20190331_004537852.jpg"
		description = "2020-02-13T22:25:26+00:00"

	[[params.portfolio.gallery]]
		image = "at-the-bear/inCollage_20190719_220346327.jpg"
		thumb = "at-the-bear/thumbs/inCollage_20190719_220346327.jpg"
		title = "Title inCollage_20190719_220346327.jpg"
		description = "2020-02-13T22:25:26+00:00"

	[[params.portfolio.gallery]]
		image = "at-the-bear/inCollage_20190810_220233379.jpg"
		thumb = "at-the-bear/thumbs/inCollage_20190810_220233379.jpg"
		title = "Title inCollage_20190810_220233379.jpg"
		description = "2020-02-13T22:25:27+00:00"

	[[params.portfolio.gallery]]
		image = "at-the-bear/inCollage_20191004_213939697.jpg"
		thumb = "at-the-bear/thumbs/inCollage_20191004_213939697.jpg"
		title = "Title inCollage_20191004_213939697.jpg"
		description = "2020-02-13T22:25:27+00:00"

	[[params.portfolio.gallery]]
		image = "at-the-bear/inCollage_20191004_230902313.jpg"
		thumb = "at-the-bear/thumbs/inCollage_20191004_230902313.jpg"
		title = "Title inCollage_20191004_230902313.jpg"
		description = "2020-02-13T22:25:27+00:00"

	[[params.portfolio.gallery]]
		image = "at-the-bear/inCollage_20191004_234555540.jpg"
		thumb = "at-the-bear/thumbs/inCollage_20191004_234555540.jpg"
		title = "Title inCollage_20191004_234555540.jpg"
		description = "2020-02-13T22:25:27+00:00"

	[[params.portfolio.gallery]]
		image = "at-the-bear/inCollage_20191005_175724039.jpg"
		thumb = "at-the-bear/thumbs/inCollage_20191005_175724039.jpg"
		title = "Title inCollage_20191005_175724039.jpg"
		description = "2020-02-13T22:25:27+00:00"

	[params.recentposts]
		hide  = false
		title = "Recent blog posts"

	[params.contact]
		hide  = false
		title = "Get In Touch"
		content = "Accumsan pellentesque commodo blandit enim arcu non at amet id arcu magna. Accumsan orci faucibus id eu lorem semper nunc nisi lorem vulputate lorem neque lorem ipsum dolor."

		# This can be exact coordinates or a searchable address in google maps
		gmaps_address = "39.7889055,-120.5443524"
		address = [
			"1234 Somewhere Rd.",
			"Nashville, TN 00000",
			"United States"
		]
		phone = "000-000-0000"

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "ziroby@gmail.com"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Name"
			email = "Email"
			message = "Message"
			submit = "Send message"


# Menu links that appear on the left sidebar
[[menu.main]]
	name = "Home"
	url  = "/"
	weight = 0

[[menu.main]]
        name = "About"
	url = "about"
	weight = 5
[[menu.main]]
	name = "Blog"
	url  = "post/"
	weight = 10
